package com.particlesdevs.photoncamera.processing.opengl.postpipeline;

import android.graphics.Bitmap;
import android.graphics.Point;
import android.opengl.GLES30;
import com.particlesdevs.photoncamera.util.Log;

import static android.opengl.GLES31.GL_CLAMP_TO_EDGE;
import static android.opengl.GLES31.GL_LINEAR;

import com.particlesdevs.photoncamera.app.PhotonCamera;
import com.particlesdevs.photoncamera.processing.ImageFrame;
import com.particlesdevs.photoncamera.processing.opengl.GLBasePipeline;
import com.particlesdevs.photoncamera.processing.opengl.GLCoreBlockProcessing;
import com.particlesdevs.photoncamera.processing.opengl.GLDrawParams;
import com.particlesdevs.photoncamera.processing.opengl.GLFormat;
import com.particlesdevs.photoncamera.processing.opengl.GLImage;
import com.particlesdevs.photoncamera.processing.opengl.GLInterface;
import com.particlesdevs.photoncamera.processing.opengl.GLProg;
import com.particlesdevs.photoncamera.processing.opengl.GLTexture;
import com.particlesdevs.photoncamera.processing.opengl.postpipeline.RotateWatermark;
import com.particlesdevs.photoncamera.processing.opengl.scripts.GLHistogram;
import com.particlesdevs.photoncamera.processing.parameters.ResolutionSolution;
import com.particlesdevs.photoncamera.processing.render.NoiseModeler;
import com.particlesdevs.photoncamera.processing.render.Parameters;
import com.particlesdevs.photoncamera.processing.ultrahdr.GainMapComputer;
import com.particlesdevs.photoncamera.settings.PreferenceKeys;
import com.particlesdevs.photoncamera.util.Allocator;
import com.particlesdevs.photoncamera.util.BufferUtils;

import java.nio.ByteBuffer;
import java.util.ArrayList;

public class PostPipeline extends GLBasePipeline {
    public ByteBuffer stackFrame;
    public GLTexture FusionMap;
    public GLTexture GainMap;
    /**
     * Linear display gain of the shot: the ARK exposure (ArkStats / ArkAe).
     */
    public float linearDisplayGain = 1.0f;
    /** Noise sigma of the frame (variance stabilised units) estimated by NiceDenoise; 0 = not measured. */
    public float niceNoiseSigma = 0f;
    /** ARK tone of the LMC hybrid: state handed from ArkStats to ArkCombine / ArkSharpenGuard; null outside that route. */
    public ArkTone.State ark;
    /**
     * Display-domain exposure curve (1D float LUT) generated by
     * {@link AutoExposureCurve} from the linear histogram. Null when that node did not run.
     */
    public GLTexture exposureCurve;
    public ArrayList<Bitmap> debugData = new ArrayList<>();
    public Point cropSize;
    /** Final output size of the hybrid 2x pipeline (sensor orientation), produced by {@link HybridFinalResize}; null = output at rawSize. */
    public Point finalSize;
    public boolean finalResized;
    float regenerationSense = 1.f;
    float AecCorr = 1.f;

    // Ultra HDR state.
    /**
     * When true, the first run captures the linear (post-demosaic) buffer so
     * the scene-anchored gain-map pass can measure pre-local-tone-map scene
     * energy.
     */
    /**
     * Highest scene-referred value the raw can now reach. Opposed-colour highlight
     * inpainting reconstructs clipped photosites above 1.0, and downstream stages
     * need to know that instead of assuming 1.0. Ported with the inpainting group
     * from upstream PhotonCamera.
     */
    /**
     * Scene white above display white, measured by {@link AutoExposureCurve}
     * (>= 1.0; 1.0 when whites already sit at display white). initial.glsl
     * divides its input by it so whites anchor at 1.0 before the SDR tone
     * chain, whose clamps would otherwise destroy the over-range highlight
     * detail the inpaint-opposed reconstruction produced.
     */
    public float adaptiveWhitePoint = 1.0f;
    public float rawClipLevel = 1.0f;
    public boolean captureDemosaic = false;
    private boolean mCaptured = false;
    /**
     * CPU copy of the post-demosaic linear buffer (survives GLTexture.closeAll).
     * Backed by a native {@link Allocator} malloc - at 50 MP this snapshot is
     * ~768 MB (16 B/pixel), far above the Java heap growth limit, so it must
     * not be a Java-accounted direct ByteBuffer. Must be freed via
     * {@link #releaseDemosaicLinear()}.
     */
    public ByteBuffer demosaicLinear;
    public Point demosaicLinearSize;

    public PostPipeline() {
        super("PostPipeline");
    }

    public int getRotation() {
        int rotation = mParameters.cameraRotation;
        String TAG = "ParseExif";
        Log.d(TAG, "Gravity rotation:" + PhotonCamera.getGravity().getRotation());
        Log.d(TAG, "Sensor rotation:" + PhotonCamera.getCaptureController().mSensorOrientation);
        return rotation;
    }

    @SuppressWarnings("SuspiciousNameCombination")
    private Point getRotatedCoords(Point in) {
        switch (getRotation()) {
            case 0:
            case 180:
                return in;
            case 90:
            case 270:
                return new Point(in.y, in.x);
        }
        return in;
    }

    private void computeNoise(Parameters parameters) {
        NoiseModeler modeler = parameters.noiseModeler;
        if (modeler == null || modeler.computeModel == null
                || modeler.computeModel.length < 3
                || modeler.computeModel[0] == null
                || modeler.computeModel[1] == null
                || modeler.computeModel[2] == null) {
            Log.w("PostPipeline", "Missing noise model; using conservative fallback");
            noiseS = 1.0e-4f;
            noiseO = 1.0e-6f;
            return;
        }
        noiseS = modeler.computeModel[0].first.floatValue() +
                modeler.computeModel[1].first.floatValue() +
                modeler.computeModel[2].first.floatValue();
        noiseO = modeler.computeModel[0].second.floatValue() +
                modeler.computeModel[1].second.floatValue() +
                modeler.computeModel[2].second.floatValue();
        noiseS /= 3.f;
        noiseO /= 3.f;
        Log.d("PostPipeline", "NoiseS:" + noiseS + "\n" + "NoiseO:" + noiseO);
        noiseO = Math.max(noiseO, Float.MIN_NORMAL);
        noiseS = Math.max(noiseS, Float.MIN_NORMAL);
    }

    public Bitmap Run(ByteBuffer inBuffer, Parameters parameters) {
        mParameters = parameters;
        mSettings = PhotonCamera.getSettings();
        workSize = new Point(mParameters.rawSize.x, mParameters.rawSize.y);
        computeNoise(parameters);
        captureDemosaic = mSettings.ultraHdr;
        mCaptured = false;
        linearDisplayGain = 1.0f;
        niceNoiseSigma = 0f;
        // Drop any stale reference from a previous run; the texture itself is
        // reclaimed by GLTexture.closeAll().
        exposureCurve = null;
        adaptiveWhitePoint = 1.0f;
        rawClipLevel = 1.0f;
        Point rawSliced = parameters.rawSize;
        cropSize = new Point(parameters.rawSize);
        finalSize = null;
        finalResized = false;
        if (!mSettings.ultraHdr && parameters.hybridFinalSize != null
                && parameters.hybridFinalSize.x < parameters.rawSize.x && parameters.hybridFinalSize.y < parameters.rawSize.y) {
            // The output image, the crop and the rotation work on the resized image (HybridFinalResize before Rotate).
            finalSize = new Point(parameters.hybridFinalSize);
            rawSliced = new Point(finalSize);
            cropSize = new Point(finalSize);
        }
        if (PhotonCamera.getSettings().aspect169) {
            if (rawSliced.x > rawSliced.y) {
                rawSliced = new Point(rawSliced.x, rawSliced.x * 9 / 16);
            } else {
                rawSliced = new Point(rawSliced.y * 9 / 16, rawSliced.y);
            }
            cropSize =  new Point(rawSliced);
        }
        Point rotatedSize = getRotatedCoords(rawSliced);
        if (mParameters.rawSize.x * mParameters.rawSize.y < ResolutionSolution.smallRes) {
            GLDrawParams.TileSize = 8;
        } else {
            GLDrawParams.TileSize = 256;
        }
        GLFormat format = new GLFormat(GLFormat.DataType.SIMPLE_8, 4);
        GLImage output = new GLImage(rotatedSize, format, false);
        // No full-frame readback buffer: runAllToBitmap() copies the last pass tile by tile into the bitmap.
        GLCoreBlockProcessing glproc = new GLCoreBlockProcessing(rotatedSize, output, format, GLDrawParams.Allocate.None);
        glint = new GLInterface(glproc);
        stackFrame = inBuffer;
        glint.parameters = parameters;

        BuildDefaultPipeline();
        // The last pass is rendered tile by tile straight into the bitmap (GLCoreBlockProcessing.drawBlocksToBitmap):
        // the peak is the GL working set + the bitmap, without the full-frame readback buffer (~200 MB at 50 MP) that
        // used to sit next to one or the other (textures + buffer, then buffer + bitmap).
        Bitmap res = runAllToBitmap();
        // The GL working set (three FP16 textures = 1.2 GB on the 50 MP Sabre 2x grid) is released right after the
        // readback. closeAll must run while the EGL context is still current; the linear scene buffer was snapshotted
        // to CPU from inside LinearExposure.Run, so the gain-map pass still works later.
        try {
            GLES30.glFinish();
        } catch (Exception ignored) {}
        GLTexture.closeAll();
        return res;
    }

    /** Called from LinearExposure.Run to keep the linear scene buffer. */
    public void captureDemosaicLinear(GLTexture tex) {
        if (mCaptured || demosaicLinear != null) return;
        // FLOAT_16 textures are read back as GL_FLOAT (4 B/channel, RGBA),
        // i.e. 16 B/pixel: ~768 MB at 50 MP - above the Java heap growth
        // limit, so the snapshot is allocated in native memory instead
        // (same backing as the pipeline's other large I/O buffers).
        int size = tex.mSize.x * tex.mSize.y * 4 * 4;
        ByteBuffer buf = Allocator.allocate(size);
        if (buf == null) {
            Log.e("PostPipeline", "Linear scene snapshot allocation of " + size + " B failed; Ultra HDR will fall back to SDR");
            return;
        }
        tex.BindBuffer();
        tex.textureBuffer(new GLFormat(GLFormat.DataType.FLOAT_16, 4), buf);
        buf.rewind();
        demosaicLinear = buf;
        demosaicLinearSize = new Point(tex.mSize.x, tex.mSize.y);
        mCaptured = true;
    }

    /** Frees the native linear scene snapshot; safe to call repeatedly. */
    public void releaseDemosaicLinear() {
        if (demosaicLinear != null) {
            Allocator.free(demosaicLinear);
            demosaicLinear = null;
        }
        demosaicLinearSize = null;
    }

    /**
     * Ultra HDR gain-map pass (scene-anchored): fusion local tone mapping
     * compresses clipped highlights below display white inside the rendering
     * chain, so no comparison of pipeline outputs can recover them. Instead
     * this pass measures the pre-local-tone-map scene energy directly from the
     * captured post-demosaic buffer ({@link #demosaicLinear}):
     *
     * <ol>
     *   <li>render the scene-luma plane L (linear luminance, rotated/cropped to
     *       match the stored base) via {@code ultrahdr/sceneluma}</li>
     *   <li>anchor the two midtones to each other:
     *       {@code k = median(linearized base luma) / median(L)} - matching
     *       medians makes the scene/render ratio grow monotonically as the SDR
     *       signal saturates, so clipped cores always dominate</li>
     *   <li>encode {@code log2((L·k + eps) / (baseLuma + eps))} via
     *       {@code ultrahdr/gainmap}</li>
     * </ol>
     *
     * Scene content above the anchor with a saturated SDR signal yields real,
     * multi-stop boost; the anchor itself is exactly zero and everything below
     * is floored to identity. Independent of AutoExposure and local tone
     * mapping state.
     *
     * @param sdr   the SDR (display-encoded) base rendition, already computed by {@link #Run}
     * @param down  downsample factor per axis for the gain map (1/down^2 pixels)
     * @param scale total log2 range of the encoding; must equal {@link GainMapComputer#SCALE}
     * @return the encoded RGBA8 gain map plus its dimensions, downsample and scale
     */
    public GainMapRaw RunHDRGainMap(ByteBuffer inBuffer, Parameters parameters, Bitmap sdr, int down, float scale) {
        if (demosaicLinear == null || demosaicLinearSize == null) {
            throw new IllegalStateException("Linear buffer missing; Run() must complete first with ultraHdr enabled");
        }
        mParameters = parameters;
        mSettings = PhotonCamera.getSettings();
        workSize = new Point(mParameters.rawSize.x, mParameters.rawSize.y);
        computeNoise(parameters);
        captureDemosaic = false;
        Point rawSliced = parameters.rawSize;
        cropSize = new Point(parameters.rawSize);
        if (PhotonCamera.getSettings().aspect169) {
            if (rawSliced.x > rawSliced.y) {
                rawSliced = new Point(rawSliced.x, rawSliced.x * 9 / 16);
            } else {
                rawSliced = new Point(rawSliced.y * 9 / 16, rawSliced.y);
            }
            cropSize =  new Point(rawSliced);
        }
        Point rotatedSize = getRotatedCoords(rawSliced);
        // The gain map must be pixel-aligned with the stored SDR base; any
        // size/orientation mismatch displaces the boost field from the scene.
        // Fail loudly -> caller falls back to a plain SDR JPEG.
        if (sdr.getWidth() != rotatedSize.x || sdr.getHeight() != rotatedSize.y) {
            throw new IllegalStateException("SDR/gain-map size mismatch: sdr="
                    + sdr.getWidth() + "x" + sdr.getHeight()
                    + " map=" + rotatedSize.x + "x" + rotatedSize.y);
        }
        GLFormat format = new GLFormat(GLFormat.DataType.FLOAT_16, 4);
        // Dummy output keeps the original driver path (Direct allocation) while
        // GLImage/GLCoreBlockProcessing null-guards prevent the NPE.
        GLImage output = new GLImage(rotatedSize, format, false);
        GLCoreBlockProcessing glproc = new GLCoreBlockProcessing(rotatedSize, output, format, GLDrawParams.Allocate.Direct);
        // Do not destroy the previous EGL context here: PostPipeline historically
        // leaked the first context until final pipeline.close(), and destroying
        // it before GLTexture re-creation caused SEGV_MAPERR on waffle/Adreno.
        // The leaked context is reclaimed at final pipeline.close().
        glint = new GLInterface(glproc);
        stackFrame = inBuffer;
        glint.parameters = parameters;

        // Defensive: the measured linear buffer must match the pipeline input size,
        // otherwise the scene sampling is out of bounds and the gain map is garbage.
        if (demosaicLinearSize.x != workSize.x || demosaicLinearSize.y != workSize.y) {
            throw new IllegalStateException("Linear buffer size " + demosaicLinearSize
                    + " does not match workSize " + workSize
                    + "; cannot measure scene plane");
        }

        GLTexture gainTex = null;
        try {
            demosaicLinear.rewind();
            GLTexture linTex = new GLTexture(demosaicLinearSize,
                    new GLFormat(GLFormat.DataType.FLOAT_16, 4), demosaicLinear);
            GLImage sdrImage = new GLImage(sdr);
            GLTexture sdrTex = new GLTexture(sdrImage);
            // The direct copy of the SDR bitmap (~200 MB at 50 MP) is only needed for the upload; drop it now instead of
            // at the end of the pass (GLImage.close releases the buffer, the bitmap stays with the caller).
            sdrImage.close();

            // Lens-shading GainMap for flat-fielding the scene plane (see sceneluma.glsl).
            // Must match the map used on the SDR path (VivoNiceRgb) so the ratio
            // is vignette-free. Re-upload from Parameters; the pipeline's GainMap field
            // was deleted by Run()'s closeAll().
            try {
                Point mapSz = mParameters.mapSize != null ? mParameters.mapSize : new Point(1, 1);
                float[] gmArr = mParameters.gainMap;
                if (gmArr == null || gmArr.length < 4) {
                    gmArr = new float[]{1f, 1f, 1f, 1f};
                    mapSz = new Point(1, 1);
                }
                gainTex = new GLTexture(mapSz, new GLFormat(GLFormat.DataType.FLOAT_16, 4),
                        BufferUtils.getFrom(gmArr), GL_LINEAR, GL_CLAMP_TO_EDGE);
            } catch (Exception e) {
                Log.e("PostPipeline", "Failed to upload GainMap for UltraHDR, falling back to identity", e);
                gainTex = new GLTexture(new Point(1, 1), new GLFormat(GLFormat.DataType.FLOAT_16, 4),
                        BufferUtils.getFrom(new float[]{1f, 1f, 1f, 1f}), GL_LINEAR, GL_CLAMP_TO_EDGE);
            }

            // Scene-luma plane at full resolution, pixel-aligned with the base.
            GLTexture lTex = new GLTexture(new Point(rotatedSize.x, rotatedSize.y),
                    new GLFormat(GLFormat.DataType.FLOAT_16, 4));
            lTex.BufferLoad();

            GLProg prog = glint.glProgram;
            prog.useAssetProgram("ultrahdr/sceneluma");
            prog.setTexture("InputBuffer", linTex);
            prog.setTexture("GainMap", gainTex);
            prog.setVar("rotate", rotationIndex());
            prog.setVar("mirror", parameters.mirror ? 1 : 0);
            prog.setVar("cropSize", cropSize);
            prog.setVar("rawSize", mParameters.rawSize);
            GLES30.glDisable(GLES30.GL_SCISSOR_TEST);
            GLES30.glBindFramebuffer(GLES30.GL_FRAMEBUFFER, lTex.mBuffer);
            GLES30.glViewport(0, 0, rotatedSize.x, rotatedSize.y);
            prog.draw();
            checkGlError("scene-luma draw");

            // Anchor: medians of the rendering and of the scene plane. Median
            // (not top-percentile) anchoring is required - with large blown
            // regions both top percentiles land inside the same saturated area
            // and would cancel out, while matched medians keep the scene/render
            // ratio growing monotonically toward saturation.
            final int histSize = 256;
            float lMed;
            float sMedLin;
            GLHistogram hist = new GLHistogram(prog, histSize);
            try {
                lMed = Math.max(histogramMedian(hist.Compute(lTex), histSize), 1e-4f);
                float sMedDisp = histogramMedian(hist.Compute(sdrTex), histSize);
                sMedLin = srgbToLinear(sMedDisp);
            } finally {
                hist.close();
            }
            float anchor = sMedLin / lMed;
            Log.d("PostPipeline", "UltraHDR anchor:" + anchor + " Lmed:" + lMed + " SmedLin:" + sMedLin);

            int gw = Math.max(1, rotatedSize.x / down);
            int gh = Math.max(1, rotatedSize.y / down);
            GLTexture outTex = new GLTexture(new Point(gw, gh), new GLFormat(GLFormat.DataType.SIMPLE_8, 4));
            outTex.BufferLoad();

            prog.useAssetProgram("ultrahdr/gainmap");
            prog.setTexture("InputBuffer", sdrTex);
            prog.setTexture("LBuffer", lTex);
            prog.setVar("uAnchor", anchor);
            prog.setVar("uDown", down);
            prog.setVar("uScale", scale);
            prog.setVar("uEps", GainMapComputer.DECODE_OFFSET);
            GLES30.glBindFramebuffer(GLES30.GL_FRAMEBUFFER, outTex.mBuffer);
            GLES30.glViewport(0, 0, gw, gh);
            prog.draw();
            checkGlError("gain-map comparison draw");

            ByteBuffer gm = outTex.textureBuffer(new GLFormat(GLFormat.DataType.SIMPLE_8, 4), false);
            gm.position(0);
            Bitmap gmBmp = Bitmap.createBitmap(gw, gh, Bitmap.Config.ARGB_8888);
            gmBmp.copyPixelsFromBuffer(gm);

            sdrTex.close();
            linTex.close();
            lTex.close();
            outTex.close();
            if (gainTex != null) {
                try { gainTex.close(); } catch (Exception ignored) {}
                gainTex = null;
            }
            return new GainMapRaw(gmBmp, gw, gh, down, scale);
        } finally {
            if (gainTex != null) {
                try { gainTex.close(); } catch (Exception ignored) {}
            }
            GLTexture.closeAll();
            // Consume-once: the snapshot is only needed for this pass.
            releaseDemosaicLinear();
        }
    }

    @Override
    public void close() {
        // Safety net for paths where the gain-map pass never ran.
        releaseDemosaicLinear();
        super.close();
    }

    private void checkGlError(String what) {
        int err = GLES30.glGetError();
        if (err != GLES30.GL_NO_ERROR) {
            Log.e("PostPipeline", "GL error 0x" + Integer.toHexString(err) + " in " + what);
        }
    }

    /** Rotation index used by the rotate-style shaders: 90->3, 180->2, 270->1, else 0. */
    private int rotationIndex() {
        switch (getRotation()) {
            case 90: return 3;
            case 180: return 2;
            case 270: return 1;
            default: return 0;
        }
    }

    /**
     * Median of a {@link GLHistogram} result across RGB channels: the bin
     * where the cumulative count from the top crosses half of all samples.
     * Returns the bin value normalized to [0,1].
     */
    private static float histogramMedian(int[][] result, int histSize) {
        long total = 0L;
        for (int i = 0; i < histSize; i++) {
            total += (long) result[0][i] + (long) result[1][i] + (long) result[2][i];
        }
        if (total <= 0L) return 0f;
        final long threshold = total / 2L;
        long acc = 0;
        for (int i = histSize - 1; i >= 0; i--) {
            acc += (long) result[0][i] + (long) result[1][i] + (long) result[2][i];
            if (acc > threshold) return (float) i / (float) (histSize - 1);
        }
        return 1f;
    }

    private static float srgbToLinear(float c) {
        c = Math.min(Math.max(c, 0f), 1f);
        return c <= 0.04045f ? c / 12.92f : (float) Math.pow((c + 0.055) / 1.055, 2.4);
    }

    public static class GainMapRaw {
        public final Bitmap bitmap;
        public final int w;
        public final int h;
        public final int down;
        public final float scale;
        GainMapRaw(Bitmap bitmap, int w, int h, int down, float scale) {
            this.bitmap = bitmap;
            this.w = w;
            this.h = h;
            this.down = down;
            this.scale = scale;
        }
    }

    private void BuildDefaultPipeline() {
        if (mParameters.vivoNiceRgb == null)
            throw new IllegalStateException("no merge route: the photo pipeline takes the RGB of the LMC hybrid or SCAM HDR");
        remosaicApplied = mParameters.remosaicDone;
        // One tone for both routes: the ARK tone (ArkStats -> ArkFusion -> [ArkLumaSharpen] -> ArkCombine).
        Log.i("NICE_PIPELINE","route="+(PreferenceKeys.isHybridShot()?"LMC_hybrid":"SCAM_HDR")
                +" import=NICE_linear_RGB WB_LSC=SCAMERA TCE=not_connected"
                +" postDenoise=bypassed"
                +" tone=ARK (ArkStats/ArkFusion/ArkCombine)"
                +"; actual node order/timings follow in Pipeline log");
        add(new VivoNiceRgb());
        add(new HighlightRecovery());
        add(new NiceDenoise());
        // Sharpening "ark" = ArkCam's own (ArkLumaSharpen before the delta; RawTherapee after the tone only with
        // ark_post_sharp), else rt | scam | off after the tone. Weight of the post-tone sharpening where the fusion lifted
        // the shadows (ArkSharpenGuard), 0 = none.
        final String sharpen = PreferenceKeys.niceSharpenMode();
        final boolean arkSharp = "ark".equals(sharpen);
        final boolean arkPostSharp = arkSharp ? PreferenceKeys.hybridSwitch("ark_post_sharp", false) : !"off".equals(sharpen);
        final float arkGuard = arkPostSharp ? Math.max(0f, PreferenceKeys.hybridValue("ark_sharp_guard", 0.5f)) : 0f;
        // The ArkCam 1.23 photo tone (tone_port.md 7.1): its own AE, fusion and AgX. LinearExposure only keeps the
        // Ultra HDR linear snapshot.
        if (captureDemosaic) add(new LinearExposure());
        add(new ArkStats());
        add(new ArkFusion());
        if (arkSharp) add(new ArkLumaSharpen());
        add(new ArkCombine(arkGuard));
        // ArkCam's sharpening ran before the delta (sharp mode "ark"); otherwise, or with ark_post_sharp, the chosen
        // sharpening (rt|scam, own settings) on the toned image, weakened in lifted shadows; texture only on request
        // (ArkCam has no mid-frequency boost); LMC curves only for the user's tone/gamma presets.
        final boolean texture = PreferenceKeys.hybridSwitch("ark_texture", false);
        final boolean curves = (!"off".equals(PreferenceKeys.getLmcToneCurve()) && PreferenceKeys.getLmcToneCurveStrength() > 0f)
                || (!"off".equals(PreferenceKeys.getLmcGammaCurve()) && PreferenceKeys.getLmcGammaCurveStrength() > 0f);
        Log.i("NICE_PIPELINE", "ARK tail: sharpen=" + sharpen + (arkSharp ? " (ArkLumaSharpen, post=" + arkPostSharp + ")" : "")
                + " guard=" + arkGuard + " texture=" + texture + " lmcCurves=" + curves);
        if (arkPostSharp) {
            if ("scam".equals(sharpen)) add(new NiceSharpen());
            else add(new RTSharpening());
        }
        if (arkGuard > 0f) add(new ArkSharpenGuard());
        if (texture) add(new NiceLocalContrast());
        if (curves) add(new LmcCurves());
        if (finalSize != null) add(new HybridFinalResize(finalSize, PreferenceKeys.hybridDownsampler()));
        add(new RotateWatermark(getRotation()));
    }
}
