#!/usr/bin/env python3
"""Extract PD2454 NICE tables without losing repeated cJSON object members.

No sensor-mode selection or scene inference. Generated data is consumed by
vivo-nice-tuning.h; counts alone must not be treated as a Camera2 capture plan.
"""
import argparse
import hashlib
import json
from pathlib import Path

class ObjectPairs(list):
    def one(self, key):
        values = self.all(key)
        if len(values) != 1:
            raise ValueError(f'Expected one {key!r}, got {len(values)}')
        return values[0]

    def all(self, key):
        return [value for name, value in self if name == key]


def read(path):
    def invalid(value):
        raise ValueError(f'Non-JSON constant: {value}')
    return json.loads(path.read_text(), object_pairs_hook=ObjectPairs,
                      parse_constant=invalid)


def extract(root):
    names = ('master', 'ultra', 'tele', 'periscopic')
    paths = [root / f'nice2.0_{name}.json' for name in ('params', *names)]
    docs = [read(path) for path in paths]
    for doc in docs:
        if doc.one('project') != 'PD2454':
            raise ValueError('Unsupported NICE tuning project')
    params = docs[0]
    result = {'sources': {p.name: hashlib.sha256(p.read_bytes()).hexdigest() for p in paths},
              'normal': [], 'hdr': []}
    for lens, (doc, zoom_suffix, count_suffix) in enumerate(zip(docs[1:], 'mutp', 'wutp')):
        rows = doc.one(f'g_zoom_trigger_{zoom_suffix}').all('value')
        counts = doc.one(f'g_nice_normal_frame_num_{count_suffix}').one('value')
        counts_r = doc.one(f'g_nice_normal_frame_num_{count_suffix}_r').one('value')
        special = doc.one('g_nice_normal_frame_num_t_4x4_r').one('value') if lens == 2 else counts_r
        if not (len(rows) == len(counts) == len(counts_r) == len(special)):
            raise ValueError('Mismatched zoom/count tables')
        effects = doc.one(f'g_tce_file_{zoom_suffix}').all('value')
        for row in rows:
            if len(row) != 2 or not row[0] < row[1]:
                raise ValueError('Invalid zoom interval')
        for threshold, filename in effects:
            if not isinstance(threshold, (int, float)) or not filename.endswith('.xml') or '/' in filename:
                raise ValueError('Invalid TCE effect entry')
        result['normal'].append(dict(zoom=rows, counts=counts, counts_r=counts_r,
                                     special=special, effects=effects))
    result['stagger'] = params.one('g_nice_normal_stagger_frame_num').one('value')[0]
    for kind in ('single', 'dual'):
        groups = params.one(f'g_nice_hdr_frame_num_map_{kind}').all('')
        seen = set()
        for group in groups:
            camera = [(k, v) for k, v in group if k.startswith('TUNING_CAMERA_TYPE_')]
            if len(camera) != 1 or len(camera[0][1]) != 1:
                raise ValueError('Ambiguous camera group')
            lens = camera[0][1][0]
            if lens in seen:
                raise ValueError('Duplicate camera group')
            seen.add(lens)
            for name, node in group.one('NiceHDRFrameInfoGroup'):
                values = node.one('value')
                if len(values) != 3 or not isinstance(values[2], list):
                    raise ValueError('Malformed HDR entry')
                a, b, ev = values
                if any(type(x) is not int for x in (a, b, *ev)) or a < 0 or b < 0 or a+b > 16 or len(ev) > 32:
                    raise ValueError('HDR entry outside recovered capacities')
                # Preserve exactly, including dual LivePhoto's three-element EV
                # vector. Do not impose an invented 2*count rule on every row.
                result['hdr'].append(dict(dual=kind == 'dual', lens=lens, name=name,
                                          count0=a, count1=b, ev=ev))
    return result


def header(data):
    lines = ['// Generated by tools/extract_vivo_nice_tuning.py; do not edit.', '#pragma once',
             '// Included within vivo_nice::tuning after the table types.']
    lines += [f'// {name}: {sha}' for name, sha in data['sources'].items()]
    def ints(values):
        return '{' + ','.join(map(str, values)) + '}'
    def floats(value):
        return repr(float(value)) + 'f'
    for lens, row in enumerate(data['normal']):
        lines.append(f'inline constexpr ZoomRow zoom{lens}[] = {{')
        for (lo, hi), count, reduced, special in zip(row['zoom'], row['counts'], row['counts_r'], row['special']):
            lines.append('    {' + ','.join((floats(lo), floats(hi), str(count), str(reduced), str(special))) + '},')
        lines.append('};')
        lines.append(f'inline constexpr EffectRow effects{lens}[] = {{')
        for threshold, name in row['effects']:
            lines.append('    {' + floats(threshold) + ',' + json.dumps(name) + '},')
        lines.append('};')
    lines.append('inline constexpr LensTable lenses[] = {')
    for lens, row in enumerate(data['normal']):
        lines.append(f'    {{zoom{lens},{len(row["zoom"])},effects{lens},{len(row["effects"])}}},')
    lines += ['};', f'inline constexpr int staggerCount = {data["stagger"]};',
              'inline constexpr HdrRow hdrRows[] = {']
    for row in data['hdr']:
        lines.append('    {' + ','.join((str(row['dual']).lower(), str(row['lens']), json.dumps(row['name']),
                      str(row['count0']), str(row['count1']), str(len(row['ev'])), ints(row['ev']))) + '},')
    return '\n'.join(lines + ['};', ''])


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument('nice_directory', type=Path)
    ap.add_argument('--header', type=Path, required=True)
    args = ap.parse_args()
    data = extract(args.nice_directory)
    args.header.write_text(header(data))
    print(f'Extracted {len(data["normal"])} lens tables and {len(data["hdr"])} HDR rows; repeated members retained')

if __name__ == '__main__':
    main()
